### ISSUE TITLE
OperationIds are no longer optional since the addition of validation in version 4.2.10

### ISSUE THREAD

**Issue by JorickPepin** [zircote/swagger-php#1153]
As noted here https://github.com/nelmio/NelmioApiDocBundle/issues/1967, the optional aspect of operationIds indicated in [the specifications](https://swagger.io/docs/specification/paths-and-operations/#operationid) is no longer respected since the addition of the operationId uniqueness check in version 4.2.10 (#1149).

As I understand it, these identifiers must be unique if they are specified which is not mandatory. If this is the case, then null values should not be taken into account in the validation.

**Comment by DerManoMann** [comment]
Well, but that is the thing - they are specified. Optional means they are not in the spec. Having `operationId: null` in the spec does explicity set it and if that is done more than once it is duplicate.

The cause for this is here: https://github.com/nelmio/NelmioApiDocBundle/blob/master/OpenApiPhp/DefaultOperationId.php#L32.

`Generator::UNDEFINED` is a 'magic' value in swagger-php to mark a property as not set. In that case the property is 
ommitted from the output - `null` is not.

I think the reason for this 'hack' was that historically operation ids were not always unique when swagger-php generated it. However, this has changed (I think).

Furthermore, there is a simpler way of avoiding operation ids altogether and that is to drop the OperationId processor in swagger-php. 

Having said all that, I appreciate that `operationId` is a somewhat special case. Also, the spec defines it as `string`, so `null` is an invalid value in the first place....

**Comment by JorickPepin** [comment]
Thank you for the explanations and the modification :+1:

**Comment by GuilhemN** [comment]
I think the issue originates in the fact that the `null` value used to be a special value in `zircote/swagger-php` for `operationId` (here https://github.com/zircote/swagger-php/commit/70316e3411a203b73dab270f180b0f25e25f22fe#diff-95de59e4b4f717f2f8872b2209151efd4cfe46c688762478b229d88a10aaea22L166-L168), it allowed us to prevent the `OperationId` processor from defining an `operationId`.

We need this because we generate a lot of annotations in NelmioApiDocBundle, and we don't always have a file/method/line to provide to the context so it unfortunately doesn't generate unique operation ids in our case.

The issue was mitigated by https://github.com/nelmio/NelmioApiDocBundle/pull/1907 and I left the complete fix for later. If you don't like having a special case for the `null` value we could indeed also remove the `OperationId` processor on our end, let me know and we can do the change in NelmioApiDocBundle :)

**Comment by GuilhemN** [comment]
Oh actually I just checked https://github.com/zircote/swagger-php/pull/1154 and this won't do for our case as we used `null` to bypass the `OperationId` processor. I guess we should just remove it then, right?
