### ISSUE TITLE
Docs aren't generated for classes without methods

### ISSUE THREAD

**Issue by hotrush** [zircote/swagger-php#1170]
```
class SomeClass extends SomeAnotherClass
{
    /**
    * @OA\Post(
    *     path="/endpoint"
    * )
    */
    use SomeTrait;
} 
```

Example is simplified, but anyway - docs won't be generated for this class because it has no methods. If add any dummy method - it will work

**Comment by DerManoMann** [comment]
Hmm, I would consider that a PHP reflection edge case. What happens is that reflection will map the comment to the next element in the class that is detected.

In this example PHP will also ignore the annotation since the method is **before** the annotation comment:

```php
<?php

trait SomeTrait {}

class SomeClass
{
    function duh() {}

    /**
     * @OA\Post(
     *     path="/endpoint"
     * )
     */
    use SomeTrait;
}
```

Adding a property instead of a method gives us a slightly different result - `operationId` is missing as the operation is not associated with a method to handle it (the request)
```php
<?php

trait SomeTrait {}

class SomeClass
{
    /**
     * @OA\Post(
     *     path="/endpoint"
     * )
     */
    use SomeTrait;

    protected $duh;
}
```
So, the bottom line is that this is not going to work reliably unless the annotation is associated with a structural element supported by PHP reflection; the [FAQ](https://zircote.github.io/swagger-php/guide/faq#warning-required-oa-info-not-found) has some more details if you are interested...

I suppose the annotation could go into the trait but I suspect you want to re-use the trait with different endpoints?

One possible solution would be to move the annotation to class level:

```php
<?php

trait SomeTrait {}

/**
 * @OA\Post(
 *     path="/endpoint"
 * )
 */
class SomeClass
{
    use SomeTrait;
}
```
Only caveat here is that there won't be an `operationId` auto-generated, but you could easily assign one manually in the annotation in this case.

**Comment by hotrush** [comment]
> you want to re-use the trait with different endpoints

yeap

We define `operationId` manually, that's not an issue. Moved our annotations to class level, the only way that worked...
