### ISSUE TITLE
Duplicate definition on same line (attribute)

### ISSUE THREAD

**Issue by tjveldhuizen** [zircote/swagger-php#1220]
Should [`\OpenApi\Annotations\AbstractAnnotation::matchNested`](https://github.com/zircote/swagger-php/blob/e6d00f990393ea69159a1c62886527e897676560/src/Annotations/AbstractAnnotation.php#L595) also check if the `$parent` class does not start with 'OpenApi\Attributes'? When I upgrade from version 4.2.11 to 4.3.0 I get the following error, which is not given when I check for the mentioned string.

```
User Warning: Multiple @OA\Response() with the same response="200":
\CompetitietypeController->cgetAction() in /app/src/ApiController/V1/Beach/CompetitietypeController.php on line 94
\CompetitietypeController->cgetAction() in /app/src/ApiController/V1/Beach/CompetitietypeController.php on line 94
```

Indeed, a warning about a duplicate definition on the same line. The line number seems to be incorrect, the reference is to line 29 in the code below (file has 50 lines)

```php
28    #[OA\Get(summary: 'Geeft een overzicht van competitietypes', tags: ['Definitietabellen'])]
29    #[OA\Response(response: 200, description: 'Success')]
30    #[Api\Parameter\Page]
31    #[Api\Parameter\Limit]
32    #[Route(methods: ['GET'])]
33    public function cgetAction(ParamFetcherInterface $paramFetcher, PaginationService $paginationService): Response
34    {
```

**Comment by DerManoMann** [comment]
> Should [\OpenApi\Annotations\AbstractAnnotation::matchNested](https://github.com/zircote/swagger-php/blob/e6d00f990393ea69159a1c62886527e897676560/src/Annotations/AbstractAnnotation.php#L595) also check if the $parent class does not start with 'OpenApi\Attributes'?

Unfortunately no. Doing so will break quite some tests. Parent/child relations are always configured using annotations - attributes inherit those - so we always need to go back to annotations in order to get correct matches.

Its hard for me to tell what is wrong here without a way to reproduce this error - would it be possible for you to create a simple repository that isolates the issue? I know that some changes made here are not that compatible with framework bundles and it would be cool to be able to debug some of those issues...

**Comment by tjveldhuizen** [comment]
I'll try to make a reproduction. I'm using this in a Symfony project in which I use https://github.com/nelmio/NelmioApiDocBundle. The base path is on the class level, this specific method has no extension of that base path. In 4.2.11 that was working.

I tried to understand the structure of this project, to be able to debug this, however lack of ability to focus on that forced me to remain using 4.2.11 for the time being.

**Comment by DerManoMann** [comment]
If you could isolate which actual release does include the breaking change that would be helpful too. There are a few more 4.2.xx versions before 4.3.0...

**Comment by manowark** [comment]
The bug comes after upgrade to https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.9.0

**Comment by javer** [comment]
@DerManoMann Here is the small reproducer of the issue: https://github.com/javer/zircote-swagger-php-issue-1220

There is only one actual commit (excluding symfony project bootstrap): https://github.com/javer/zircote-swagger-php-issue-1220/commit/949d4d9b52f39a934b8d319be0dac97b67ca287d

When we run `bin/console nelmio:apidoc:dump` or open in the browser `/api/doc.json` - we see the following exception:
```
User Warning: Multiple @OA\Response() with the same response="200":
\ApiController->action() in src/Controller/ApiController.php on line 94
\ApiController->action() in src/Controller/ApiController.php on line 94
```

If we remove either some `Route` attribute or `ApiDoc\Operation` attribute in `ApiController` - error is gone.

**Comment by DerManoMann** [comment]
Great - so its swgger-php **or** nelmio :cry:

**Comment by DerManoMann** [comment]
> When I upgrade from version 4.2.11 to 4.3.0 I get the following error, ...

To me it seems this was not just an isolated upgrade of `swagger-php`, but a general update that would have picked up also the new nelmio version?

The fact that downgrading `swagger-php` in your reproducer repo does not help at all and also the fact that removing `nelmio` attributes '_helps_' suggest to me that the issue is unrelated to swagger-php.

Looking at the code changes `NelmioApiDocBundle` I think I know what happens:

Before using the `AttributeAnnotationFactory` the code would just instantiate the attributes and return.

However, the factory does more in that it already merges the response into the `OA\Get` (or in your repo `ApiDoc\Operation` which extends swagger-php's `OA\Operation`). Since that was not done before I would guess that happens elsewhere and now it happens twice.

**Comment by tjveldhuizen** [comment]
Indeed, even with 4.2.11 of swagger-php, it's not working, so its likely the bug is in NelmioApiDocBundle. Thanks for creating the issue there, @javer.
