### ISSUE TITLE
Can I use anonymous class for writing swagger annotation?

### ISSUE THREAD

**Issue by Dmitrijlin** [zircote/swagger-php#1285]
Hello everyone!

I have file
```php
<?php

// phpcs:disable PSR1.Classes.ClassDeclaration.MissingNamespace

/**
 * Class GetFeeSchema
 *
 * @OA\Schema(
 *  schema="GetFeeSchema",
 *  @OA\Property(
 *      property="fee",
 *      type="string"
 *  )
 * )
 */

return new class
{
};
```

When I tried to call Schema from another place I have an error `$ref "#/components/schemas/" not found for @OA\Schema()`

Is that a bug or feature?

**Comment by DerManoMann** [comment]
Somewhere in between I'd say. Since version 4 the code does use reflection in order to also support PHP attributes. That means unless your docblocks are associated with some structural element (class, interface, etc.) that can be accessed via reflection it will be skipped. So, I suppose you are out of luck here. 

If you have a lot of these perhaps moving them into a separate namespace and just give them class names according to the `schema` property would keep things tidy?

**Comment by Dmitrijlin** [comment]
Yep, thats works. I just thought, that I can use anonymous classes for writing annotations. Thanks for all.
