### ISSUE TITLE
Exclude some files from API doc generation

### ISSUE THREAD

**Issue by FallDi** [zircote/swagger-php#1299]
In version 3 parameter exclude was used to exclude some dirs/files.
However cannot found similar functionality in version4.

Is it possible to add it to v4?
<img width="855" alt="exclude" src="https://user-images.githubusercontent.com/4299295/185937276-71f52371-a68f-41c7-898f-e9ab4d0cac6d.png">

v3
<img width="890" alt="v3" src="https://user-images.githubusercontent.com/4299295/185943004-107f08e1-20e3-4bf0-a91d-d715294e7302.png">

**Comment by DerManoMann** [comment]
On the command line this option still exists.

In the `Generator` class itself it was removed as it is just a special case of passing in a Symfony `Finder` instance.
Both
```
    public static function scan(iterable $sources, array $options = []): ?OpenApi
```
and
```
    public function generate(iterable $sources, ?Analysis $analysis = null, bool $validate = true): ?OpenApi
```
accept a `Finder` instance as `$sources`.

So, looking at what the command line tool does, we can see that programmatically you can just use the `Util` class to archive the same as before:
```
$openapi = $generator
    // ..
    ->generate(Util::finder($paths, $exclude, $pattern));
```
In other words, instead of passing `$paths`, `$exlucde` and `$pattern` into the `Generator` methods you use them to set up the finder yourself and then pass that one in as the `$sources` parameter. This means you are not limited by what `Util::finder()` can do and can set up the `Finder` whichever way you need.

**Comment by FallDi** [comment]
Ou, I see. Will use `Finder`, many thanks!
