### ISSUE TITLE
schemes cannot be set

### ISSUE THREAD

**Issue by pgyf** [zircote/swagger-php#1326]
https://petstore.swagger.io/

![git](https://user-images.githubusercontent.com/3365344/195756268-8e8f26c1-9111-44df-85cd-f2a0a82d3f44.png)

**Comment by DerManoMann** [comment]
I am sorry, but this issue is a bit light on details. We'd need a few more details, for example:
* The relevant bit of yaml/json that contains the schemes list
* The annotations / attributes that set the schemes
* Maybe the swagger-php and PHP version

Generally, in order to have multiple schemes you'd need a `@OA\Server` annotation somewhere, something like https://github.com/zircote/swagger-php/blob/master/Examples/misc/OpenApiSpec.php#L33

Maybe you are missing that?

**Comment by pgyf** [comment]
@DerManoMann 
Yes, you are right. Thank you very much
