### ISSUE TITLE
`Doctrine\DBAL\Types\VarDateTimeImmutableType` not found

### ISSUE THREAD

**Issue by VladimirCreator** [zircote/swagger-php#1566]
```
Error: Class "Doctrine\DBAL\Types\VarDateTimeImmutableType" not found in .../vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/DateTimeImmutableType.php:8
```

what does it even mean?

**Comment by DerManoMann** [comment]
Looks like your classloader is not set up correctly - unlikely to be an issue with swagger-php itself. swagger-php requires classloading in order to be able to use reflection to inspect the PHP code it is scanning.
A couple of issues around class loading are explained in the [FAQ](https://zircote.github.io/swagger-php/guide/faq.html).

**Comment by carlos-algms** [comment]
Are you sure it's not a Laravel 11 issue? 
it seems this class doesn't exist anymore.

**Comment by DerManoMann** [comment]
Well, maybe both ;)

From the message the doctrine class is referenced in `not found in .../vendor/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine/DateTimeImmutableType.php:8`, so I would think that means the version of Carbon references it.

So it looks like a mismatch in dependencies. Only thing that comes to mind is that Laravel dropped `DBAL` as a dependency - maybe there is some dependency mismatch (assuming the app uses Laravel)?
