### ISSUE TITLE
$ref not found for @OA\Parameter()

### ISSUE THREAD

**Issue by hafezdivandari** [zircote/swagger-php#1578]
I get following warning:

```
Warning: $ref "#/components/parameters/product" not found for @OA\Parameter()
```

Using following attributes:

```php
#[OA\Parameter(
    name: 'product',
    description: "The product ID",
    in: "path",
    required: true,
    schema: new OA\Schema(type: "integer")
)]
#[OA\PathItem(
    path: "/products/{product}",
    parameters: [
        new OA\Parameter(ref: "#/components/parameters/product") // <== Doesn't accept "ref"
    ]
)]
```

But using the same approach with annotations was working fine on 3.x:

```php
/**
 * @OA\Parameter(
 *   name="product",
 *   description="The product ID",
 *   in="path",
 *   required=true,
 *   @OA\Schema(type="integer")
 * )
 *
 * @OA\PathItem(
 *   path="/products/{product}",
 *   @OA\Parameter(ref="#/components/parameters/product") // <== Was working as expected on 3.x
 * )
 */
```

**Comment by DerManoMann** [comment]
Yes, that's why there is a 4.x version :)

In 4.x all annotations/attributes in a group (same class, etc) are merged automatically. That helps avoiding too much nesting.

If you do not re-use the component then you might be ok by just removing the whole `parameters` parameter in your `PathItem`.

If you want to reuse the component you will need to assign it to it's own class/interface, etc.
This can be a dummy or perhaps the actual product model - depends on how your code is organized.

Some more details may be found int he FAQ, for example https://zircote.github.io/swagger-php/guide/faq.html#warning-required-oa-info-not-found
