### ISSUE TITLE
The Authorization specified in HeaderParameter cannot correctly try it out.

### ISSUE THREAD

**Issue by SwankyTigerYY** [zircote/swagger-php#1581]
success
#[OA\HeaderParameter(name: 'Authorization1', description: 'token', in: 'header', required: true, schema: new OA\Schema(type: 'string'))]

error
#[OA\HeaderParameter(name: 'Authorization', description: 'token', in: 'header', required: true, schema: new OA\Schema(type: 'string'))]

Is Authorization a Keyword？why？

**Comment by DerManoMann** [comment]
Could you provide some details about the error you are seeing?

**Comment by SwankyTigerYY** [comment]
![image](https://github.com/zircote/swagger-php/assets/24326903/39e79f65-75f5-486f-a750-21736bbaf75b)
![image](https://github.com/zircote/swagger-php/assets/24326903/efb2d204-47c5-42e3-a7d5-f65e6d22bc6e)

**Comment by DerManoMann** [comment]
There is nothing special about it in swagger-php. However, OpenApi has special handling for security - https://spec.openapis.org/oas/v3.1.0.html#security-scheme-object.

Instead of configuring a raw header the `OA\SecurityScheme` annotation should be used, something like:

```php
/**
 *     @OA\SecurityScheme(
 *         type="apiKey",
 *         securityScheme="http"
 *     )
 */
```

You might need to adjust `type` for your needs and perhaps also use other options depending.
