### ISSUE TITLE
About v6 - php EOL - to trigger a spark

### ISSUE THREAD

**Issue by mroeling** [zircote/swagger-php#1670]
![image](https://github.com/user-attachments/assets/ded1d51a-e068-4110-a074-2d2e41af72b2)

Appreciating the work you do in this project.  👍

Wrt the question at hand, you say 85% is using php 8.1 and up. But actually 15% should upgrade asap since 8.0 and down is already EOL. 
What would be the problem to focus just on active php versions? Perhaps do something similar as php does, so just breaking/security fixes for the older versions, and instead put the energy in 8.1 or even 8.3 support (if needed).

In the end it's your decision ofc, :)

**Comment by DerManoMann** [comment]
It is my decision and maybe I am just too much of a softie :) That is partly why I've already created the [v6] issue to keep reminding me that this is on the cards.

I think it is importand for me to remind myself that even if we are moving on the older versions are still usable. Also, there are practical issues as well. 

In some of my other openapi related projects, for example, I've already moved on to 8.1, because it gets increasingly more difficult to just get phpunit to work across more than two major versions :)

So, I think for [v5] I'd like to stick to the plan, but I would expect [v6] to happen a lot quicker after that than the change from 4 to 5.

**Comment by mroeling** [comment]
> It is my decision

Again, much appreciated!

> ... some of my other openapi related projects ...

Yes, I understand. Depending on size of team and size of projects, this can be quite a task to keep everything up to date. And always a "fight" between developing and time consuming maintenance.
