### ISSUE TITLE
Swagger-php on Heroku

### ISSUE THREAD

**Issue by uniguestDan** [zircote/swagger-php#285]
Greetings!

Running into an odd issue. I created an endpoint in my api to serve up the result of the scan function and return back the JSON result. The problem that I am running into is that on my local machine, the endpoint works exactly as expected. However, on the Heroku app, it is only giving me a subset of the expected response.

As near as I can tell, the only missing data is from the "path" spec.

Any ideas what I have either done wrong or if Heroku is doing something funny?

Thanks!

**Comment by bfanger** [comment]
Thats weird, log in to your server `heroku run bash` and try running swagger from the command line. that might expose whats going wrong.

I also a good idea to generate a static swagger.json with a [post-install-cmd](https://getcomposer.org/doc/articles/scripts.md#event-names) hook. That way the swagger.json in only generated when a new heroku image is build, instead of on every request.
