### ISSUE TITLE
Separate path and responses in separate dockblock

### ISSUE THREAD

**Issue by dimsav** [zircote/swagger-php#336]
Hello,

is it possible to define the path of an endpoint on a separate location than the rest of the endpoint details?

For example: 

```php
// routes.php

/** @SWG\Get(
 *     path="/docs"
 */
Route::get('users', 'UsersController@getUsers');
```

```php
// UsersController

 /** @SWG\Get(
 *     @SWG\Response(response="200", description="Returns users list"),
 *     @SWG\Response(response="400", description="You don't have access to this resource"),
 * )
 */
public function getUsers() {
 // 
}
```

**Comment by bfanger** [comment]
You could place a `@SWG\Path(path="/docs")` in your routes.php (which doesn't do anything), but you'd still need to add the path to the `path="/docs"` to the `@SWG\Get` in the controller, because swagger-php doesn't know about your larval routing setup is configured. 

I've always placed the swagger comments in the controllers, because that's where the documentation lives closest to the actual code.

Another idea is to write an optional framework specific [processor](https://github.com/zircote/swagger-php/tree/master/src/Processors) which infers the path based on the controller/routing setup.

**Comment by dimsav** [comment]
Thanks!
