### ISSUE TITLE
Add Swagger to require-dev causes troubles

### ISSUE THREAD

**Issue by keesschepers** [zircote/swagger-php#352]
Hello,

We are using Swagger for the documentation of our internal API. These API docs should not be available on production.

For this reason I have chosen to add Swagger to require-dev but this is causing problems like these:

`Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Swagger\Annotations\Property" in property **CLASS**::$id does not exist, or could not be auto-loaded.`

That makes sense because Swagger isn't loaded offcourse. But is there a way to ignore Swagger annotations? This didn't help me either:

`\Doctrine\Common\Annotations\AnnotationReader::addGlobalIgnoredName('Swagger');`

Also tried:

`\Doctrine\Common\Annotations\AnnotationReader::addGlobalIgnoredName('SWG\Model');`

Etc..

Can anyone help me? We are using version 1.0.0 (due to PHP upgrading issues)

cc: @jeroen-sen

**Comment by bfanger** [comment]
Could be related to https://github.com/zircote/swagger-php/issues/119

**Comment by bfanger** [comment]
You could try [DocParser->setIgnoreNotImportedAnnotations](https://github.com/doctrine/annotations/blob/58e3ca626981b6ff818f42fb57f318a6e14f361f/lib/Doctrine/Common/Annotations/DocParser.php#L281)(true) 

I'm closing this issue because we  can't fix this issue ( swagger-php is not even installed )
I hope you'll find a fitting solution.

PS. File issues to [doctrine](http://www.doctrine-project.org) when features like `addGlobalIgnoredName` don't behave as expected.
