### ISSUE TITLE
Swagger Validation Error

### ISSUE THREAD

**Issue by andcl85** [zircote/swagger-php#356]
Hello, 

I am getting an error when validating my api-docs.json file in this parameter:

```
@SWG\Parameter(
 *          name = "body",
 *          in = "body",
 *          description = "Email, new password and email token",
 *          required = true,
 *          @SWG\Schema(
 *              title = "datos",
 *              required = {"email", "password", "password_confirmation", "token"},
 *              @SWG\Property (property = "email", type = "string", example = "email@example.net"),
 *              @SWG\Property (property = "password", type = "password", example = "secret"),
 *              @SWG\Property (property = "password_confirmation", type = "password", example = "secret"),
 *              @SWG\Property (property = "token", type = "string", example = "817f15dfd932ff3228c2a7"),
 *          )
 *      ),
```

Isn't it compliant with the specification?
The error:

```
{
	"schemaValidationMessages": [
		{
			"level": "error",
			"domain": "validation",
			"keyword": "oneOf",
			"message": "instance failed to match exactly one schema (matched 0 out of 2)",
			"schema": {
				"loadingURI": "http://swagger.io/v2/schema.json#",
				"pointer": "/definitions/parametersList/items"
			},
			"instance": {
				"pointer": "/paths/~1password~1reset/post/parameters/0"
			}
		}
	]
}
```

Any help is much appreciated.
Thanks in advance.

**Comment by bfanger** [comment]
That's quite a cryptic error you've got there.

What you've deduced is that the first parameter `parameters/0` is `~1password~1reset` post, is not a _#/definitions/jsonReference_ `{ref: '...'} ` or a valid parameter _#/definitions/parameter_

But your validator **doesn't say why**, which is tricky because the cause of the validation error is burried in a tree of errors/decisions. 

**Things you'd want the validator to say:**  

1) `type = "password"` is not a valid type, use "array", "boolean", "integer", "null", "number", "object" or "string"`

Because: The _#/definitions/parameter_ should identified as an  _#/definitions/bodyParameter_ but it isn't because the "schema" doesn't match _#/definitions/schema_ which references the http://json-schema.org/draft-04/schema#/properties/type for the `type` property. which states that is should be an _#/definitions/simpleTypes_ or an array of _#/definitions/simpleTypes_ and "password" isn't in the list of posible simpleTypes.

2) The `@SWG\Schema()` is missing `type="object"`

And maybe others validation issues i've missed.

---

swagger-php tries to generate valid swagger.json and emit warnings when it's invalid and i'll gladly accept pull-requests that improve the validation phase of swagger-php.

**Comment by andcl85** [comment]
Thank you very much, @bfanger.
It validates without errors now :)
