### ISSUE TITLE
doctrine/annotations dependency version issue

### ISSUE THREAD

**Issue by zefj** [zircote/swagger-php#418]
doctrine/annotations from v1.5.0 upwards is no longer compatible with PHP 5.6. This package defines in it's dependencies `"doctrine/annotations": "*"`, which means composer will download the latest doctrine/annotations version, and in result break any 5.6 project due to unavailable language features.

Please bind doctrine/annotations dependency to v1.4.0 or change this package PHP compatibility information.

**Comment by bfanger** [comment]
If it breaks, then the "doctrine/annotations" package is at fault by not specifying the required php version.
composer is smart enough to install packages based on php version and specified version range.

But your issue is easily fixed by just specify the version of "doctrine/annotations" you want in your composer.json

**Comment by zefj** [comment]
Not if you use `--ignore-platform-reqs`. 

So pretty much ship broken package and let the users figure out what's broken, instead of changing one line and calling it a day? Version pinning is there for exactly this reason, there is no excuse not to use it.

**Comment by bfanger** [comment]
Version pinnig in a project composer.json is good practice. In a library we must be more liberal especially with a package that other packages also depend on to make sure composer can find a suitable version.

You broke your installation by using --ignore-platform-regs, don't blame it on others.
