### ISSUE TITLE
Is there a way to write annotations for 2 Swagger APIs in the same php repository ?

### ISSUE THREAD

**Issue by mostafaabdelbaset** [zircote/swagger-php#476]

**Comment by danydev** [comment]
This question is not really related to this project. 
You can generate multiple json by pointing to different paths to scan, then once you have multiple json files, you can modify swagger-ui's index.html to point to a different json based on a var in query string, finally you can add several links to change such query string.

**Comment by itodor** [comment]
I think this is still valid question because this project works by scanning files/folders annotations. Your solution would work if these API's would have completely different definitions and endpoints but what if i want to share the same model definition in both API's? I cant write 2 annotations so each API would read one of them? I'm currently wondering as well how to fix this.

**Comment by danydev** [comment]
And you can do it indeed, just use a "Common" folder where you put files with common annotations and put such folder in both the "paths to scan" params you'll use to generate the two different jsons

**Comment by bfanger** [comment]
Related #362, #415 

Try writing a plugin that uses [custom properties](https://github.com/zircote/swagger-php/blob/master/docs/Getting-started.md#vendor-extensions) 
For example: `x-internal-only=true` and `x-external-only=true`

**Comment by danydev** [comment]
What we're at my company (where we basically have a "customer api", a "public api" and an "internal api") is just to generate multiple json files with different path to scans (some are shared between the apis some are not).
No use of `x-internal-only`, and It works fairly well for us.
