### ISSUE TITLE
Array of objects as param

### ISSUE THREAD

**Issue by FabianPiconeDev** [zircote/swagger-php#486]
I am using version ^2.0.
I want to submit an array of objects. The following notation does not work:

    *     @SWG\Parameter(
    *          name="foo",
    *          in="query",
    *          required=true,
    *          type="array",
    *          @SWG\Items(
    *              type="object",
    *              @SWG\Property(
    *                  property="id",
    *                  type="string"
    *              ),
    *              @SWG\Property(
    *                  property="position",
    *                  type="string"
    *              )
    *          )
    *     ),

This error is thrown:

    User Notice: @SWG\Items()->type="object" not allowed inside a @SWG\Parameter() 
    must be "string", "number", "integer", "boolean", "array" in D:\...

I could do an array of json strings, but i dont like this idea. Is there any other solution?

**Comment by bfanger** [comment]
You can't document an array of object in the GET parameters because there is no standard way for servers to decode that.

Sending an array of objects is usually done in the `body` of a POST or PUT request.

> "I want to submit ..."

You'll probably should use a POST request.

However, If you really are restricted to  GET request, you can document "foo" as "string" and describe how it should look in the description. You can also set the [format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) to json, (that doesn't do anything, it's just a hint to the reader of the documentation)

**Comment by FabianPiconeDev** [comment]
Thanks for your reply/solution.
