### ISSUE TITLE
Question: How to correctly annotate an image/png response in 3.0

### ISSUE THREAD

**Issue by TomCawthorn** [zircote/swagger-php#560]
Hi there,

It looks like this question has been asked already in reference to OAS2 [here](https://github.com/zircote/swagger-php/issues/455).

Would you be able to recommend (perhaps with an example) the best way to annotate a response type of image/* [for OAS3](https://swagger.io/docs/specification/media-types/)?

![image-example](https://user-images.githubusercontent.com/7405852/43585353-cf246984-965c-11e8-8b83-0f163b59e979.png)

Thanks!

Tom

**Comment by bfanger** [comment]
To generate the OAS3 example you provided you'd write:

```php
/**
 * @OA\Get(
 *   path="/info/logo",
 *   @OA\Response(
 *     response="200",
 *     description="OK",
 *     @OA\MediaType(
 *        mediaType="image/*",
 *        @OA\Schema(type="string",format="binary")
 *     )
 *   )
 * )
 */
```

The `content` inside a `@OA\Response` is a [MediaType object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#mediaTypeObject) which allows all sorts of responses including `image/*`.

A json response can be written as:
```
*   @OA\Response(
 *     response="200",
 *    description="OK",
 *     @OA\MediaType(
 *        mediaType="json/application",
 *        @OA\Schema(type="object",...)
 *     )
 *   )
```
But because this is such a common scenario, i've created the JsonContent annotation which will [create the MediaType annotation](https://github.com/zircote/swagger-php/blob/master/src/Processors/MergeJsonContent.php) for you.

You were probably looking for a ImageContent annotation. I'd preferred it if the spec called it a Content object, so we could add a Content annotation, which is more easily discovered, but they didn't so MediaType it is.

**Comment by TomCawthorn** [comment]
Hey @bfanger,

I was wondering why I couldn't track it down! Thanks for explaining and for example.
