### ISSUE TITLE
Undefined property: OpenApi\Processors\MergeJsonContent::$_context

### ISSUE THREAD

**Issue by cristian-chiric** [zircote/swagger-php#785]
There is a small bug at:

at vendor/zircote/swagger-php/src/Processors/MergeJsonContent.php:30

 > Logger::notice('Unexpected '.$jsonContent->identity() .' in ' . $parent->identity() . ' in ' . $this->_context);

Solution:

> $this->_context should be replaced with $jsonContent->_context

**Comment by Doqnach** [comment]
See PR #786 

This looks to fix the same thing as https://github.com/zircote/swagger-php/pull/777/files#diff-fc981ecc7c4b6ef671e291895ecb7f88 does, but referencing a different context...
If I understand the code correctly I would say that PR #777 looks correct since the surrounding code has $parent as its context.

pinging @piratadelfuturo and @DerManoMann

**Comment by DerManoMann** [comment]
I agree with @Doqnach - the message is talking about the parent where the invalid nested element was found. In practical terms it doesn't seem to make a difference, though.

Other than that, same question here that I asked over at #777 - could the PR please be extended to:
a) fix `MergeXmlContent` (same issue)
b) for both processors add 2 simple tests for a) no parent and b) invalid parent

In any case, not sure how to progress either of the PRs without @bfanger....

**Comment by yudina-m** [comment]
Was it fixed?

**Comment by DerManoMann** [comment]
#800 should have fixed this.
