### ISSUE TITLE
A couple (refactoring) questions

### ISSUE THREAD

**Issue by DerManoMann** [zircote/swagger-php#793]
So, as you might have noticed I am happy to change things around to make them more consistent and (re-)usable. Before going any further I'd like to have a quick discussion about a few things that might be controversal...

1. Code Style
  Are there any objections to switching from `squizlabs/php_codesniffer` to `friendsofphp/php-cs-fixer`?
  To me this would give more fine grained control over things like unused imports and a lot of other tweaks.
1. Logging
  I haven't looked closely into that yet, but getting a `trigger_error` for each notice and warning by default seems a bit much to me. While at it it might be nice to add PSR logging support
1. Use of static methods
  Somewhat related to the logging issue. In my experience using static methods makes it a lot harder for others to use/customize code. In particular for a library this is not the best way. I'd be keen to refactor some of that away while trying to keep things as much as possible BC.

**Comment by bfanger** [comment]
1. Code Style
I believe `friendsofphp/php-cs-fixer` is also available in vscode, so that is fine.

2. Logging
At first glance i found PSR logging too much work to implement, and I'd rather not add another  dependency. PSR logging is still possible, The only `trigger_error` is inside Logger.php.

Inspired by Laravel facades, when calling `Logger::warning($e);` the implementation is not static but uses call a method on a dynamicly swappable $instance. As long as that object has a `log($err, $type)` method  it works. `Logger::$instance = new MyPSRLogger()`

In case of the logger this even taken one step further where the default fallback instance has a dynamic closure. `Logger::getInstance()->log = function ($err, $type) { ... }`

3. Use of static methods
Agree, `Util:finder` comes to mind as one that would be nice it it was more configurable. 
But beware that it comes with the cost of more boilerplate and extra complexity, it a balancing act.

Ii see this more as a utility than a library, I expect the default use to be:
```php
$openapi = \OpenApi\scan('/path/to/project');
header('Content-Type: application/x-yaml');
echo $openapi->toYaml();
```
and not much customisation, i could be wrong, but i don't think removing the static methods will greatly increase the number of plugins.

**Comment by DerManoMann** [comment]
Fair enough :)
