### ISSUE TITLE
Reference to SecurityScheme

### ISSUE THREAD

**Issue by JotaJota96** [zircote/swagger-php#854]
I have created the following structure

```
    /**
     * @OA\SecurityScheme(
     *     type="apiKey",
     *     in="header",
     *     securityScheme="api_key",
     *     name="Authorization"
     * )
     */
```

and I would like to reference it similar to how I reference JSON object definitions

```
     *   @OA\RequestBody(
     *        @OA\JsonContent(ref="#/components/schemas/UserDTO"),
     *   ),
```

is this possible? how?
Taking advantage of the opportunity, I would like to ask: where can I find more documentation about the notation?
Thanks

**Comment by Doqnach** [comment]
http://spec.openapis.org/oas/v3.0.3#security-scheme-object

and

http://spec.openapis.org/oas/v3.0.3#security-requirement-object

Note that Swagger-PHP follows OpenApi in it's notation, so if you take the notation from the spec it should be hopefully easy to convert that to PHPDOC for Swagger-PHP.

My question to you is what you are hoping to achieve by doing so? Because I find it hard to think of a use-case why you would want to do such a thing?

**Comment by JotaJota96** [comment]
Sorry for my English, maybe I didn't explain myself well.

After checking a little more, I found something that solved my problem.

What I was looking for was this:

```
* @OA\Get(
*     ....
*     security={{"api_key": {}}},
*     ....
* )
```

You can remove this Issue
