### ISSUE TITLE
Swagger Annotation will cause any latency issues.

### ISSUE THREAD

**Issue by pvagare** [zircote/swagger-php#863]
Hi Team,

I have observed that we need to include use "OpenApi\Annotations as OA" namespace at the top of controller or at the top of models. 
I am using the Symfony 5.1 PHP framework.

Just wanted to confirm Is it cause the latency issue? Meaning Is the annotation will parsed for every request ? 
Also Just wanted to know. Can I Add this as dev time dependencies ? Meaning I don't want to install swagger php on production build.

Look forward to your response !

Thanks !

**Comment by Doqnach** [comment]
`use OpenApi\Annotations as OA;` is only needed if you want to write the PHPDOC using the shorthand `@OA\Xxxx` for annotations.

It is not Swagger-PHP that triggers any parsing on a request, but some other library you are using might? Swagger-PHP will only parse PHPDOC when explicitly asked for it (via `OpenApi::scan()`).

The import itself will not give any noticeable latency issues.

Installing Swagger-PHP as `require-dev` can give issues because of that import and Symfony parsing those PHPDOC (using doctrine) when warming up/creating cache.

**Comment by pvagare** [comment]
@Doqnach thanks !
