### ISSUE TITLE
Using this tool for golang source code

### ISSUE THREAD

**Issue by mauserzjeh** [zircote/swagger-php#917]
Is there a way to parse annotations from golang source code? 

I would like to use this library to simply parse the api documentation from the source code but I haven't manage to make it work. I am constantly getting two notices.

- "Notice: Required @OA\Info() not found in ..."
- "Notice: Required @OA\PathItem() not found in ..."

I annotated the code according to the specification, and also set the "pattern" option to "*.go". Is there something I am completely missing or is there anything more required to make this work? I successfully generated OpenAPI documentation out of php code before, but doesn't this tool work for any files as long as the comment-syntax of the language is the same?

Thanks in advance.

**Comment by DerManoMann** [comment]
Not quite - the file parser uses the PHP tokenizer to parse the file. That allows to map docblocks to classes/methods/properties etc...
Sounds interesting, though; could you provide perhaps a single file example to play around with?

**Comment by mauserzjeh** [comment]
Here is a single example file, that has the basic annotations I tried to use, to test the tool. 
[main.zip](https://github.com/zircote/swagger-php/files/6180790/main.zip)

**Comment by DerManoMann** [comment]
Jeez, just came back to this! Sorry, too much to do.

I had a play and there are two issues right now. One is eay to fix, one is a bit trickier...
1. Your comment needs to start with `/**` instead of just `/*` - this is the syntax for a PHP docblock as opposed to just a comment.
2. Once the comment is fixed, things will work if the file starts with `<?php` :) The parser will ignore everything outside as that is legal in PHP and will just be returned.  This is how PHP web pages used to work - mixing content and code ;)

I guess it would be possible to wrap things in a pre-processor that is run prior to processing those files...
A simple solution could be to process all files (recursively) into a tmp folder and prepend `<?php` to all of them. Then you can run the `openapi` CL tools against that.

**Comment by mauserzjeh** [comment]
Actually I didn't bother too much with it and ended up creating the openapi document with hand. It took the same effort as commenting the code according to the docs. Thanks for your reply though :)

**Comment by nandaniya480-BH** [comment]
kljkhkjtfjhy5fg
