### ISSUE TITLE
OperationId processor leaks internal code structure and does not work with multiple annotations on one controller

### ISSUE THREAD

**Issue by Tobion** [zircote/swagger-php#930]
The OperationId processor adds the controller class/method as operationId to the OpenAPI definition. This is problematic because:
1. it leaks the internal code structure as also pointed out in #916
2. the operationId MUST be unique according to the OpenAPI spec. But the controller is not necessarily unique if you have multiple operations on the same controller. this is a normal workflow, e.g. to handle several http methods with the same controller. in this case the generated OpenAPI definition is invalid due to the non-unique operationId. an example for this is in https://github.com/Tobion/OpenAPI-Symfony-Routing/blob/master/tests/Fixtures/SeveralRoutesOnOneAction/Controller.php

For these reason I would suggest to remove this processor from the default processors. It should only be enabled on demand.

**Comment by DerManoMann** [comment]
Been a while since I looked at the specs - if the id must be unique, is it valid to omit it? If so, I'd agree that removing the processor is the better solution.

Also, I suppose adding the method might help with uniqueness in the case where security is not an issue.

Also also reminds me that better support for managing processors would be nice to make this a much more useful (and used) feature.

**Comment by Tobion** [comment]
Yes operationId must be unique but is not required.

**Comment by dbu** [comment]
if it would be configurable whether to output the operationId or not, people who use it for some usecase (maybe debuggin?) could leave it on and others could disable it.

**Comment by DerManoMann** [comment]
Addressed in #942 and #946
